apiVersion: v1
kind: Service
metadata:
  name: fish-game-backend-service
spec:
  selector:
    app: fish-game-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
